### ISSUE TITLE
matchicons.lua:1034: bad argument #1 to 'tonumber' (value expected)

### ISSUE THREAD

**Issue by bw1faeh0** [chrisant996/clink-gizmos#5]
Hi,

as early adopter I tried the new `matchicons.lua` this morning. 

After enabling it (`clink set matchicons.enable true`) and restarting my shell, I got following error after the first keystroke:

![grafik](https://github.com/chrisant996/clink-gizmos/assets/29235332/6cc77b46-abb9-41eb-bb6c-9409c88802dc)

I was trying to `cd` into an directory.

clink version: 1.6.4.1dd7ec

I'm disabling it for now.

**Comment by chrisant996** [comment]
Thanks for trying it and reporting the error.

I pushed a fix.

The error happened when the `DIRX_NERD_FONT_VERSION` and `DIRX_ICON_SPACING` environment variables were not set.  They're related to [dirx](https://github.com/chrisant996/dirx), and I have them set on my machine because I've been testing the dirx program.
